version: '3.8'

services:
  api:
    container_name: gb-api
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:example@gb-monogodb:27017
      - NODE_ENV=development
      - JWT_SECRET=sosecret
      - JWT_EXPIRES_IN=30d
    networks:
      - gb-network

  db:
    container_name: gb-monogodb
    image: mongo:4.4.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    logging:
      driver: none
    networks:
      - gb-network

networks:
  gb-network:
    driver: bridge
