version: '3.8'

services:
  api:
    container_name: gb-api
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    networks:
      - gb-network

  db:
    container_name: gb-monogodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    logging:
      driver: none
    networks:
      - gb-network

networks:
  gb-network:
    driver: bridge